-- Generated by Matugen; loaded through pcall so a missing fragment is non-fatal.
hl.config({
    general = {
        col = {
            active_border = {
                colors = { "rgba({{colors.primary.default.hex_stripped}}ff)", "rgba({{colors.tertiary.default.hex_stripped}}ff)" },
                angle = 45,
            },
            inactive_border = "rgba({{colors.outline_variant.default.hex_stripped}}aa)",
        },
    },
    decoration = {
        shadow = { color = "rgba({{colors.shadow.default.hex_stripped}}99)" },
        glow = {
            color = "rgba({{colors.primary.default.hex_stripped}}55)",
            color_inactive = "rgba({{colors.outline_variant.default.hex_stripped}}22)",
        },
    },
})
