pragma Singleton

import QtQuick

// Generated by Matugen. Keep semantic roles stable for every shell panel.
QtObject {
    readonly property color background: "{{colors.background.default.hex}}"
    readonly property color surface: "{{colors.surface.default.hex}}"
    readonly property color surfaceLow: "{{colors.surface_container_low.default.hex}}"
    readonly property color surfaceContainer: "{{colors.surface_container.default.hex}}"
    readonly property color surfaceHigh: "{{colors.surface_container_high.default.hex}}"
    readonly property color surfaceBright: "{{colors.surface_bright.default.hex}}"
    readonly property color foreground: "{{colors.on_surface.default.hex}}"
    readonly property color foregroundVariant: "{{colors.on_surface_variant.default.hex}}"
    readonly property color primary: "{{colors.primary.default.hex}}"
    readonly property color primaryForeground: "{{colors.on_primary.default.hex}}"
    readonly property color primaryContainer: "{{colors.primary_container.default.hex}}"
    readonly property color primaryContainerForeground: "{{colors.on_primary_container.default.hex}}"
    readonly property color secondary: "{{colors.secondary.default.hex}}"
    readonly property color secondaryContainer: "{{colors.secondary_container.default.hex}}"
    readonly property color tertiary: "{{colors.tertiary.default.hex}}"
    readonly property color tertiaryContainer: "{{colors.tertiary_container.default.hex}}"
    readonly property color outline: "{{colors.outline.default.hex}}"
    readonly property color outlineVariant: "{{colors.outline_variant.default.hex}}"
    readonly property color error: "{{colors.error.default.hex}}"

    // Compatibility aliases used by existing components during incremental reloads.
    readonly property color bg: background
    readonly property color panel: surfaceContainer
    readonly property color panelHigh: surfaceHigh
    readonly property color text: foreground
    readonly property color muted: foregroundVariant
    readonly property color accent: primary
    readonly property color border: outlineVariant

    readonly property int radius: 18
    readonly property int cardRadius: 14
    readonly property int motionMs: 190
    readonly property int fastMotionMs: 145
}
