background = #12121c
foreground = #e3e1ef
cursor-color = #c0c1ff
cursor-text = #1000a9
selection-background = #1b00eb
selection-foreground = #e1e0ff
palette = 0=#0d0d17
palette = 1=#ffb4ab
palette = 2=#dcbaf0
palette = 3=#cdc0e9
palette = 4=#c0c1ff
palette = 5=#573c69
palette = 6=#4b4263
palette = 7=#e3e1ef
palette = 8=#918f9c
palette = 9=#93000a
palette = 10=#dcbaf0
palette = 11=#cdc0e9
palette = 12=#c0c1ff
palette = 13=#f3daff
palette = 14=#e9ddff
palette = 15=#e3e1ef
window-padding-x = 14
window-padding-y = 12
window-decoration = false
background-opacity = 0.94
cursor-style = block
shell-integration = fish
