pragma Singleton

import QtQuick

// Generated by Matugen. Keep semantic roles stable for every shell panel.
QtObject {
    readonly property color background: "#101318"
    readonly property color surface: "#101318"
    readonly property color surfaceLow: "#191c21"
    readonly property color surfaceContainer: "#1d2025"
    readonly property color surfaceHigh: "#282a2f"
    readonly property color surfaceBright: "#36393f"
    readonly property color foreground: "#e1e2e9"
    readonly property color foregroundVariant: "#c4c6d0"
    readonly property color primary: "#a9c7ff"
    readonly property color primaryForeground: "#003062"
    readonly property color primaryContainer: "#254777"
    readonly property color primaryContainerForeground: "#d7e3ff"
    readonly property color secondary: "#bdc7dc"
    readonly property color secondaryContainer: "#3e4759"
    readonly property color tertiary: "#dcbce1"
    readonly property color tertiaryContainer: "#55405a"
    readonly property color outline: "#8e9099"
    readonly property color outlineVariant: "#44474f"
    readonly property color error: "#ffb4ab"

    readonly property color bg: background
    readonly property color panel: surfaceContainer
    readonly property color panelHigh: surfaceHigh
    readonly property color text: foreground
    readonly property color muted: foregroundVariant
    readonly property color accent: primary
    readonly property color border: outlineVariant

    readonly property int radius: 18
    readonly property int cardRadius: 14
    readonly property int motionMs: 190
    readonly property int fastMotionMs: 145
}
