pragma Singleton

import QtQuick

// Generated by Matugen. Quickshell consumes this singleton directly.
QtObject {
    readonly property color bg: "#131318"
    readonly property color panel: "#1f1f25"
    readonly property color panelHigh: "#2a292f"
    readonly property color text: "#e4e1e9"
    readonly property color muted: "#c8c5d0"
    readonly property color accent: "#c0c1ff"
    readonly property color border: "#46464f"
    readonly property color error: "#ffb4ab"
    readonly property int radius: 14
    readonly property int motionMs: 180
}
